language: node_js
node_js:
 - 8

before_install:
 - npm install yarn -g

install:
 - yarn install
 - yarn build
 - yarn info we-edit --json > info.json
 - export LATEST=$(node -p "require('./info.json').data['dist-tags'].latest")
 - export CURRENT=$(node -p "require('./packages/we-edit/package.json').version")
 - yarn build

before_deploy:
 - cd packages/we-edit

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 skip_cleanup: true
 on:
  branch: master
  condition: "$LATEST != $CURRENT"
